language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  include:
    -
      php: 7.1
      env: 'HIGHEST_LOWEST="update" STABILITY="RC"'
    -
      php: 7.0.11
    -
      php: 5.6
    -
      php: 5.5
      env: 'HIGHEST_LOWEST="update --prefer-lowest"'
    -
      php: 5.5
      env: 'HIGHEST_LOWEST="require symfony/console:^2"'

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer config --unset platform.php
  - 'composer config minimum-stability ${STABILITY-stable}'
  - 'composer -n ${HIGHEST_LOWEST-install} --prefer-dist'
  - composer why symfony/console

script:
  - vendor/bin/phpcs --standard=PSR2 -n src
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v
